version: '3.8'

services:
  nextjs-app:
    build: .
    ports:
      - '80:3001'
    #environment:
    #  NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
